name: Jest-Heroku Pipeline

on:
  push:
    branches: [master]

jobs: 
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Repository
        uses: actions/checkout@v2
      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies"
          npm install --legacy-peer-deps
      - name: Run Eslint
        run: |
          echo "Running eslint"
          npm run lint
        env:
          CI: true
  JestTest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies"
          npm install --legacy-peer-deps
      - name: Run Jest Tests
        run: |
          echo "Running Jest Tests"
          npm run test
        env:
          CI: true